global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'matddung76@gmail.com'
        from: 'matddung76@naver.com'
        smarthost: 'smtp.naver.com:465'
        auth_username: ${SPRING_MAIL_USERNAME}
        auth_password: ${SPRING_MAIL_PASSWORD}
        auth_identity: ${SPRING_MAIL_USERNAME}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']