version: '3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: lotto
      MYSQL_USER: lotto
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    image: junhyuk1376/backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/lotto
      SPRING_DATASOURCE_USERNAME: lotto
      SPRING_DATASOURCE_PASSWORD: 1234

  frontend:
    build: ./frontend
    image: junhyuk1376/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=ec2-3-39-227-55.ap-northeast-2.compute.amazonaws.com:8080
      - REACT_APP_OAUTH2_REDIRECT_URI=ec2-3-39-227-55.ap-northeast-2.compute.amazonaws.com:3000/oauth2/redirect

volumes:
  db_data: