version: '3'

services:
  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build: ./backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/lotto
      SPRING_DATASOURCE_USERNAME: lotto
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mariadb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: lotto
      MYSQL_USER: lotto
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"

volumes:
  jenkins_home:
