global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8080']
    basic_auth:
      username: 'admin@admin.a'
      password: 'admin'

  - job_name: 'frontend'
    static_configs:
      - targets: [ 'frontend:3000' ]

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb:3306']

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'mariadb'
    static_configs:
      - targets: [ 'mariadb-exporter:9104' ]